# Generated by Django 3.2.7 on 2024-02-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assigned_studentreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('place', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('sid', models.CharField(max_length=150)),
                ('fid', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='class_schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typee', models.CharField(max_length=150)),
                ('fid', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('host_key', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='course_assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=150)),
                ('std_name', models.CharField(max_length=150)),
                ('sid', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='course_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('details', models.CharField(max_length=150)),
                ('startdate', models.CharField(max_length=150)),
                ('enddate', models.CharField(max_length=150)),
                ('amount', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='course_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=150)),
                ('course', models.CharField(max_length=150)),
                ('c_id', models.CharField(max_length=150)),
                ('amount', models.CharField(max_length=150)),
                ('card_name', models.CharField(max_length=150)),
                ('card_no', models.CharField(max_length=150)),
                ('cvv', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='facultyreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('course', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='leave_applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=150)),
                ('fid', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('reason', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='studentreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('place', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('st_type', models.CharField(max_length=150)),
            ],
        ),
    ]
