# Generated by Django 3.2.7 on 2024-02-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educonnect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='study_materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('details', models.CharField(max_length=150)),
                ('file', models.CharField(max_length=150)),
                ('fid', models.CharField(max_length=150)),
            ],
        ),
    ]
