# Generated by Django 3.2.7 on 2024-02-10 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educonnect', '0002_study_materials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study_materials',
            old_name='fid',
            new_name='sid',
        ),
    ]
