# Generated by Django 5.0.2 on 2024-03-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("educonnect", "0004_chats"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course_payment",
            old_name="card_name",
            new_name="order_id",
        ),
        migrations.RenameField(
            model_name="course_payment",
            old_name="card_no",
            new_name="payment_id",
        ),
        migrations.RemoveField(
            model_name="course_payment",
            name="cvv",
        ),
        migrations.AddField(
            model_name="course_payment",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
