# Generated by Django 3.2.7 on 2024-03-10 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educonnect', '0006_auto_20240310_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study_materials',
            name='sid',
        ),
    ]
