# Generated by Django 3.2.7 on 2024-03-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educonnect', '0007_remove_study_materials_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreg',
            name='disability_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='studentreg',
            name='disability_status',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10),
        ),
    ]
