# Generated by Django 3.2.7 on 2024-03-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educonnect', '0008_auto_20240312_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='study_materials',
            name='s_id',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
