# Generated by Django 3.2.7 on 2024-03-17 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educonnect', '0009_study_materials_s_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study_materials',
            name='s_id',
        ),
    ]
