# Generated by Django 3.2.7 on 2024-03-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educonnect', '0010_remove_study_materials_s_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='study_materials',
            name='youtube_link',
            field=models.URLField(blank=True),
        ),
    ]
