# Generated by Django 3.2.7 on 2024-03-21 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educonnect', '0011_study_materials_youtube_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study_materials',
            old_name='youtube_link',
            new_name='video_link',
        ),
    ]
